# The proposal
<!--
This is where the proposal should be outlined. 
-->

## Overview

The present project enhances the [_geometa_](https://cran.r-project.org/package=geometa) package for handling the new ISO 19115-3 geographic information standard as part of its object-oriented data model developed with [R6](https://cran.r-project.org/package=R6). 

The user community, especially data managers working in research national institutes and international organizations, will take advantage of the features to start adopting the new standard for managing their geographic metadata, progressively promoted in Geographic information management web platforms, especially those from the [OpenSource Geospatial Foundation](https://www.osgeo.org/) (OSGeo) such as [GeoNetwork](https://www.osgeo.org/projects/geonetwork/), [PyCSW](https://www.osgeo.org/projects/pycsw/) or [GeoNode](https://www.osgeo.org/projects/geonode/).

<!--
At a high-level address what your proposal is and how it will address the problem identified. Highlight any benefits to the R Community that follow from solving the problem. This should be your most compelling section.
-->

## Detail

The object-oriented data model developed with [R6](https://cran.r-project.org/package=R6) will be enhanced, introducing the following features:
* add mechanism to switch from the ISO 19115-1/19115-2 data model to ISO 19115-3 for manipulating metadata objects
* adapt classes covered by both models to accomodate changes introduced with ISO 19115-3, and add new classes defined by ISO 19115-3 only
* enhance the metadata validator (based on ISO 19115-1/19115-2/19115-3 schemas)

<!--
Go into more detail about the specifics of the project and it delivers against the problem.

Depending on project type the detail section should include:

 - [ ] Minimum Viable Product
 - [ ] Architecture
 - [ ] Assumptions
-->