# Success
<!-- 
Projects should have a definition of done that is measurable, and a thorough understanding going in of what the risks are to delivery 
-->

## Definition of done
<!-- 
What does success look like? 
-->

ISO 19115-3 is integrated into the _geometa_ data model, and fully exploitable by the geographic information management user community.

The ISO 19115-3 standard integration in _geometa_ is measured through the standards coverage summary available at [https://github.com/eblondel/geometa/blob/master/inst/extdata/coverage/geometa_coverage_summary.md](https://github.com/eblondel/geometa/blob/master/inst/extdata/coverage/geometa_coverage_summary.md) as well as the detailed classes/binding inventory at [https://github.com/eblondel/geometa/blob/master/inst/extdata/coverage/geometa_coverage_inventory.csv](https://github.com/eblondel/geometa/blob/master/inst/extdata/coverage/geometa_coverage_inventory.csv) generated automatically by scanning the _geometa_ classes & methods and comparing them to the ISO 19115-3 schemas.

## Measuring success
<!-- 
How will we know when success is achieved, what markers can we use along the way 
-->

Success will be the result of multiple measures, including:

* Package tested code with clear quality assurance indicators made of unit and integration tests
* Package improvements and new features released through CRAN
* Performance and Usability (including available and easy-to-understand documentation)


## Future work
<!-- 
How could this be extended / developed in the future by yourself and/or the community in general?
-->

Future work and perspectives derived from this project may included:

* the support for ISO 19115-3 automated metadata production through [_geoflow_](https://github.com/r-geoflow/geoflow) and automated publication into open plateforms from the [OpenSource Geospatial Foundation](https://www.osgeo.org/) (OSGeo) such as [GeoNetwork](https://www.osgeo.org/projects/geonetwork/), [PyCSW](https://www.osgeo.org/projects/pycsw/) or [GeoNode](https://www.osgeo.org/projects/geonode/).
* the assessment of the outputs of the [RConsortium Object-Oriented Programming Working Group](https://github.com/RConsortium/OOP-WG) such as the S7 package as possible way to enhance the object-oriented data model implemented in _geometa_.


## Key risks

The major technical risk of this project relates to ensuring the backward compatibility of geometa with ISO 19115-1 / 2 standards. This risk will be mitigated by consolidating the battery of unit / integration tests to cover ISO 19115-1, 2 and 3 standards.

In-kind contributions to the present project may be considered from external sources, possibly through handover to some contributors listed in the project _Signatories_, in case some extra effort would be required in relation with the technical delivery effort estimates and expected timeline.

