# Project plan

## Start-up phase

The activities can start immediately as the _geometa_ package does already have a GitHub repository. The package has a release cycle in place jointly operated between GitHub, CRAN, and Zenodo for DOI management. The package is released under MIT License. The framework for testing the _geometa_ package is already operational, based on GitHub actions.

<!--
Covering the planning phase, this section should provide a relatively detailed plan of how work will start on the project. This section is important because projects need to get up and running quickly.


 - [ ] Setting up collaboration platform inc. code for contributors etc.
 - [ ] Licence decisions
 - [ ] Reporting framework
-->


## Technical delivery

<!--
Covering the actual delivery of the project this section should provide at least a high-level the implementation. 

Including target dates is really important as you need to be committed and the ISC need to have a means of tracking delivery
-->

The implementation of the ISO 19115-3 standard in _geometa_ can be split into several activities / milestones that are listed below together with an effort estimate and an expected delivery date:

* **Milestone 1**: Support for ISO 19115-5 schemas and namespaces; and capacity of _geometa_ to switch between standards (ISO 19115-1/2 vs. ISO 19115-3)
  * Effort: 5 days
  * Expected delivery: **2023-07-15**
* **Milestone 2** Enhanced capacity to monitor ISO standards coverage including coverage of ISO 19115-3 schemas in the _geometa_ data model
  * Effort: 2 days
  * Expected delivery: **2023-07-31**
* **Milestone 3**: Enhanced capacity to inherit ISO 19115 codelists (through parsing of ISO Codelist catalogues) and application to both ISO 19115-1/2 vs. 19115-3
  * Effort: 3 days
  * Expected delivery: **2023-08-31**
* **Milestone 4**: Evolutive maintenance of ISO 19115 classes already existing in the _geometa_ data model for their adaptation to be inteoperable with the ISO 19115-3 standard. This includes the inclusion of additional fields, new methods, and controls over methods field of application (depending on their availability in ISO 19115-1/2 vs. ISO 19115-3)
  * Effort: 10 days
  * Expected delivery: **2023-12-31**
* **Milestone 5**: Support for new classes introduced with ISO 19115-3
  * Effort: 5 days
  * Expected delivery: **2024-01-31**

Jointly with these activities:

* The battery of unit tests will be extended to cover the new standard and ensure backward compatibility with ISO 19115-1/2.
* the R documentation will be progressively updated and checked through quality controls (Github Actions to perform `R CMD Check` in view of releasing the new features on CRAN)

## Other aspects

<!--
Covering non-technical activities like on-going publicity, paper preparation, discussion groups etc. that might be required to facilitate successful delivery of the project.

 - [ ] Announcement post
 - [ ] Delivery blog post
 - [ ] Twitter
 - [ ] UseR!
 - [ ] ISC meetings
-->

Apart from announcements on the package Github page, public advertising of the work will be done through:

* ISC meetings, upon request of the R Consortium ISC for tracking delivery
* Technical oral presentations and/or posters in international conferences (depending on the timeline, features accepted, and available travel funds), such as the useR conference or FOSS4G. Other sources of grants/fundings will be sought to cover eventual conference fees and related travel costs.
* Announcements through the [LinkedIn](https://www.linkedin.com) professional network, as public posts on R users groups eg. https://www.linkedin.com/groups/77616/



